import Head from "next/head";
import Image from "next/image";
import {Container, Box} from "@mui/material";
import backgroundLeft from '../../public/backgroundLeft.png';
import backgroundRight from '../../public/backgroundRight.png';
import title from '../../public/title.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
          sx={{
            backgroundImage: `url(${backgroundLeft.src}), url(${backgroundRight.src})`,
            backgroundRepeat: 'no-repeat, no-repeat',
            backgroundPosition: 'center, center center',
            backgroundSize: '100% 100%',
            minHeight: '100vh',
          }}
          disableGutters={true}
          maxWidth={false}
      >
        <Box
            sx={{
              paddingTop: '68px',
              paddingRight: '233px',
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'flex-end',
            }}
        >
          <Image src={title} alt='Title' width={332} height={95} />
        </Box>
        <Box
            sx={{
              height: '150px',
              width: '100%',
              background: 'linear-gradient(#9EDF25, #1E2E00)',
              backgroundRepeat: 'no-repeat, no-repeat',
              position: 'fixed',
              bottom: 0,
            }}
        />

      </Container>

    </>
  );
}
